---
apiVersion: v1
kind: Pod
metadata:
  name: extractor
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  restartPolicy: Never
  volumes:
    - name: shared-pvc
      persistentVolumeClaim:
        claimName: shared-pipeline-pvc
  containers:
    - name: extractor
      image: f5vwells/file-extractor:{{ .Values.Global.ImageVersions.file_extractor }}
      volumeMounts:
        - name: shared-pvc
          mountPath: /opt/test_results
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
