---
apiVersion: batch/v1
kind: Job
metadata:
  name: jtl-processor-job
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      activeDeadlineSeconds: 120
      restartPolicy: Never
      volumes:
        - name: shared-pvc
          persistentVolumeClaim:
            claimName: shared-pipeline-pvc
      containers:
        - name: processor
          image: f5vwells/jtl-processor:{{ .Values.Global.ImageVersions.jtl_processor }}
          args: ["-o", "/opt/test_results/jtl.summary.csv", "-m", "-t", "/opt/test_results", "/opt/test_results/jmeter.jtl.log"]
          volumeMounts:
            - name: shared-pvc
              mountPath: /opt/test_results
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
