---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pipeline-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.Global.PipelinePvc.StorageRequest }}
